In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("data.xlsx")

print(df)

In [4]:
print(df)

  Product    City  Sales
0  Laptop    Pune  75000
1  Mobile  Mumbai  30000
2  Tablet    Pune  20000
3  Laptop   Delhi  80000
4  Mobile    Pune  25000
5  Tablet  Mumbai  22000
6  Laptop  Mumbai  70000
7  Mobile   Delhi  28000
8  Tablet   Delhi  21000

In [5]:
df.isnull()

   Product   City  Sales
0    False  False  False
1    False  False  False
2    False  False  False
3    False  False  False
4    False  False  False
5    False  False  False
6    False  False  False
7    False  False  False
8    False  False  False

In [6]:
df.isnull().sum()

Product    0
City       0
Sales      0
dtype: int64

In [7]:
df.describe()

              Sales
count      9.000000
mean   41222.222222
std    25655.300514
min    20000.000000
25%    22000.000000
50%    28000.000000
75%    70000.000000
max    80000.000000

In [8]:
df.fillna(0)

  Product    City  Sales
0  Laptop    Pune  75000
1  Mobile  Mumbai  30000
2  Tablet    Pune  20000
3  Laptop   Delhi  80000
4  Mobile    Pune  25000
5  Tablet  Mumbai  22000
6  Laptop  Mumbai  70000
7  Mobile   Delhi  28000
8  Tablet   Delhi  21000

In [13]:
df.dropna()

  Product    City  Sales
0  Laptop    Pune  75000
1  Mobile  Mumbai  30000
2  Tablet    Pune  20000
3  Laptop   Delhi  80000
4  Mobile    Pune  25000
5  Tablet  Mumbai  22000
6  Laptop  Mumbai  70000
7  Mobile   Delhi  28000
8  Tablet   Delhi  21000

In [15]:
df.shape

(9, 3)

In [17]:
df.columns

Index(['Product', 'City', 'Sales'], dtype='object')

In [18]:
df.info

<bound method DataFrame.info of   Product    City  Sales
0  Laptop    Pune  75000
1  Mobile  Mumbai  30000
2  Tablet    Pune  20000
3  Laptop   Delhi  80000
4  Mobile    Pune  25000
5  Tablet  Mumbai  22000
6  Laptop  Mumbai  70000
7  Mobile   Delhi  28000
8  Tablet   Delhi  21000>

In [20]:
df.dtypes

Product    object
City       object
Sales       int64
dtype: object